spring:
  application:
    name: Wallet-Service
  profiles:
    active: dev
  
  liquibase:
    change-log: classpath:/config/liquibase/master.xml
    enabled: true
  
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  
  cache:
    type: redis

server:
  port: ${PORT:8080}
  shutdown: graceful

# values come from provided outsource configurations f.g Vault
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:15m}

app:
  lock:
    wait-seconds: 5
    lease-seconds: 30
    max-retries: 3
    base-backoff-ms: 200
    max-backoff-ms: 500

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized